### ISSUE TITLE
日本語のreadme書く

### ISSUE THREAD

**Issue by MachineHunter** [MachineHunter/pwndbg-memvisualization-enhance#32]
* 機能概要
* インストール方法
* 操作（GUIの説明、表示される情報が何なのか）
* Contribution
* どういう感じで実装したか
* 互換性
   * Linuxでしか動かん
   * 86_64のバイナリしか対応してない
   * UTF-8に対応してるOSしか対応してない
* 追加機能実装予定のもの
* Known bugs

**Comment by tigga36** [comment]
現在[こちらのブランチ](https://github.com/MachineHunter/pwndbg-memvisualization-enhance/tree/misc/readme_jp_ono)で取り急ぎ作業中（すでに作られているものがあればお互い後でmergeしましょう）

**Comment by MachineHunter** [comment]
@tigga36 
ほぼそちらのブランチで完成してるみたいなので、僕の方のブランチは消してしまって、そっちのブランチで続けましょう！
